# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g5mI2Tth68EdZVZSty1QYeucSDqbvQ0q
"""

# Sample Data
data = [
    {'Package ID': 1, 'Weight (kg)': 3, 'Distance (km)': 10, 'Delivery Type': 'Express'},
    {'Package ID': 2, 'Weight (kg)': 5, 'Distance (km)': 25, 'Delivery Type': 'Standard'},
    {'Package ID': 3, 'Weight (kg)': 2, 'Distance (km)': 5, 'Delivery Type': 'Express'},
    {'Package ID': 4, 'Weight (kg)': 6, 'Distance (km)': 15, 'Delivery Type': 'Standard'},
    {'Package ID': 5, 'Weight (kg)': 4, 'Distance (km)': 30, 'Delivery Type': 'Express'},
]

# Cost grid
cost_grid = {
    'Express': {
        'Base Cost': 10,
        'Cost per kg': 2,
        'Cost per km': 1,
    },
    'Standard': {
        'Base Cost': 5,
        'Cost per kg': 1.5,
        'Cost per km': 0.5,
    }
}

# Function to calculate the cost for a single package
def calculate_package_cost(package):
    delivery_type = package['Delivery Type']
    base_cost = cost_grid[delivery_type]['Base Cost']
    cost_per_kg = cost_grid[delivery_type]['Cost per kg']
    cost_per_km = cost_grid[delivery_type]['Cost per km']
    weight = package['Weight (kg)']
    distance = package['Distance (km)']

    total_cost = base_cost + (weight * cost_per_kg) + (distance * cost_per_km)
    return total_cost

# Calculate the cost for each package and add it to the data
for package in data:
    package['Total Cost'] = calculate_package_cost(package)

# Print the results
for package in data:
    print(f"Package ID: {package['Package ID']}, Total Cost: {package['Total Cost']:.2f}")

import shutil

# Zip the script and notebook
shutil.make_archive("/content/submission", 'zip', "/content")

from google.colab import files

# Download the zip file
files.download('/content/submission.zip')

